/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

var evenFibTotal = function(){
  var total = 2;
  var start = [1, 2];

  while(start[1] <= 4000000){
    var next = start[0] + start[1];
    if(next % 2 === 0){
      total += next;
    }
    start.shift();
    start.push(next);
  }

  return total;
}

console.log(evenFibTotal());
